In [3]:
import pandas as pd

In [ ]:
a = [1,2,3]
b = [1,2,3]
c = a
print(a==b)   #값을 비교
print(a is b)   #

# DataFrame

In [4]:
df = pd.DataFrame([["홍길동",90,80,70],["강감찬",80,78,90]])
print(df)

     0   1   2   3
0  홍길동  90  80  70
1  강감찬  80  78  90

In [7]:
nums=[1,2]
cnames = ["이름","국어","수학","영어"]
df = pd.DataFrame([["홍길동",90,80,70],["강감찬",80,78,90]],index=nums,columns=cnames)
print(df)

    이름  국어  수학  영어
1  홍길동  90  80  70
2  강감찬  80  78  90

In [8]:
table_data = {"연도":[2019,2020,2021],
              "매출":[100,130,120]}
df = pd.DataFrame(table_data)
print(df)

     연도   매출
0  2019  100
1  2020  130
2  2021  120

In [9]:
#연산 More
s1 = pd.Series([1,2,3,4],index=['a','b','c','d'])
s2 = pd.Series([2,3,7,8],index=['a','c','d','e'])
s3 = s1+s2
print(s3)

a     3.0
b     NaN
c     6.0
d    11.0
e     NaN
dtype: float64

In [11]:
data1 = {"홍길동":[90,85,70],
        "강감찬":[99,80,65],
        "이순신":[100,100,100]}
df1 = pd.DataFrame(data1)

In [15]:
data2 = {"홍길동":[100,75,80],
        "강감찬":[90,85,75],
        "을지문덕":[95,100,95]}
df2 = pd.DataFrame(data2)

In [16]:
df3 = df1+df2
print(df3)

   강감찬  을지문덕  이순신  홍길동
0  189   NaN  NaN  190
1  165   NaN  NaN  160
2  140   NaN  NaN  150

In [18]:
df3.describe()

              강감찬  을지문덕  이순신         홍길동
count    3.000000   0.0  0.0    3.000000
mean   164.666667   NaN  NaN  166.666667
std     24.501701   NaN  NaN   20.816660
min    140.000000   NaN  NaN  150.000000
25%    152.500000   NaN  NaN  155.000000
50%    165.000000   NaN  NaN  160.000000
75%    177.000000   NaN  NaN  175.000000
max    189.000000   NaN  NaN  190.000000

In [19]:
df3.var()

강감찬     600.333333
을지문덕           NaN
이순신            NaN
홍길동     433.333333
dtype: float64

In [20]:
print(df3.mean())
print(df3.mean(axis=1))

강감찬     164.666667
을지문덕           NaN
이순신            NaN
홍길동     166.666667
dtype: float64
0    189.5
1    162.5
2    145.0
dtype: float64

In [21]:
df3

   강감찬  을지문덕  이순신  홍길동
0  189   NaN  NaN  190
1  165   NaN  NaN  160
2  140   NaN  NaN  150

# 데이터 선택하기

df.head([n])앞쪽 데이터를 확인 (디폴트 n=5)

df.tail([n])앞쪽 데이터를 확인 (디폴트 n=5)

In [23]:
df3.head(2)

   강감찬  을지문덕  이순신  홍길동
0  189   NaN  NaN  190
1  165   NaN  NaN  160